# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

nginxImage: nginxinc/nginx-unprivileged:1.31.1-alpine-slim@sha256:762e8e4e5e103817c4158400fc3753c8e713ff8153b8c3afbb458ae4572bc9a3
updaterImage: registry.gitlab.com/gitlab-ci-utils/curl-jq:4.0.3@sha256:bd2cc4f9c880d277f8a42d87102d46e67ebce0f1d3a19b21b0125da9a4a44aa0
contentType: "application/json"

# runtimeDetails:  # Optional, exposes the runtime configuration under path /runtime/
#   synchronizerSerialId: 5  # Serial ID of the current synchronizer to fetch metrics
#   scanUrl: https://scan.sv.global.canton.network.xxx  # Optional, the default is the internal scan address, it's used to fetch the runtime configuration
#   tlsSkipVerify: true  # Optional, the default is false

# deploymentDetails:  # Optional, exposes static configuration under path /
#   network: "dev"
#   configDigest:
#     allowedIpRanges:
#       type: "md5"
#       value: "AAA"
#     approvedSvIdentities:
#       type: "sha256"
#       value: "BBB"
#   sv:
#     version: "0.3.3"  # Optional, the default is set to the Chart version
#   synchronizer:
#     current:
#       chainIdSuffix: "id0"
#       migrationId: 4
#       synchronizerSerialId: 5
#       version: "0.3.3"  # Optional, the default is set to the Chart version
#     successor:
#       chainIdSuffix: "id1"
#       migrationId: 4
#       synchronizerSerialId: 6
#       version: "0.3.4"
#     legacy: null

# istioVirtualService:  # Optional, configures Istio VirtualService for routing
#   host: "info.example.com"
#   gateway: "istio-gateway-example"

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: "0"
    memory: 32Mi

nodeSelector: {}
tolerations: []
affinity: {}
