name: Remind to backport PRs to release branches
on:
  pull_request:
    types: [opened, reopened]
    paths:
      - cluster/deployment/**
      - cluster/configs/**
      - '**/expected.json'

jobs:
  add-backport-reminder:
    runs-on: ubuntu-24.04
    steps:
        - uses: canton-network/splice-shared-gha/actions/backport_reminder@d7eb0ca758166c84d3c885e207d690766cf4993a
          with:
            pr_number: ${{ github.event.pull_request.number }}
            lookup_prod_cluster_configs: false
            token: ${{ secrets.GH_CREATE_PRS_TOKEN }}
