# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "ghcr.io/digital-asset/decentralized-canton-sync/docker"
imageName: "canton-domain"
initImageName: "postgres:14"

# Custom annotations and labels for deployed resources
pod:
  annotations: {}
  labels: {}

defaultJvmOptions: -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=75 -Dscala.concurrent.context.numThreads=12 -XX:ActiveProcessorCount=12 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/persistent-data/heap-dump-CURRENT_DATE.hprof
resources:
  limits:
    memory: 8Gi
  requests:
    cpu: "1"
    memory: 4Gi

mediator:
  persistence:
    host: postgres.sv-1.svc.cluster.local
    secretName: "postgres-secrets"
    # Optional: Provide raw strings to override the default Kubernetes secret injection.
    # This is useful for integrating with external secret management tools.
    # Note: Ensure you have the appropriate mutating webhook/injector installed in your cluster.
#    secretOverrides:
#      postgresPassword: ""

sequencer:
  persistence:
    host: postgres.sv-1.svc.cluster.local
    secretName: "postgres-secrets"
#    secretOverrides:
#      postgresPassword: ""

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:

# k8s tolerations for all deployed pods (optional)
# tolerations:

# should stakater reloader annotation be added (note: reloader needs to be installed separately)
enableReloader: true

